name: update readme mock

on:
  schedule:
    - cron: '0 0 * * *' # 毎日utc 00:00に実行
    
  push:
      branches:
        - main # mainブランチにpushされた時に実行


jobs:
  mock-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: run mock update script
        run: |
          echo "running mock update script..."
          python scripts/mock_update_article.py
          
      - name: commit and push changes (if any)
        run: |
          git config --global user.name 'kjr020'
          git config --global user.email 'johnjiro1114@gmail.com'
          git commit -am "mock update readme" || echo "no changes to commit"
          git push

